http:
  port: "8787"
  cors_allow_origins: "http://localhost:3000"

logger:
  env: "local"

postgres:
  pool_max: 2

session:
  ttl: 60m
  cookie_key: "session_id"
  cookie_path: ""
  cookie_domain: ""
  cookie_secure: false
  cookie_httponly: true

access_token:
  ttl: 1m
  signing_key: "secret"

mongodb:
  db_name: "sso"